const menu = [
    {
      id: 1,
      title: 'Chicken and Waffles [breakfast]',
      category: 'breakfast',
      price: 55.99,
      img: './images/item-1.jpeg',
      desc: 'The recipe was invented in jazz clubs in New York, or in the 1700s when the waffle iron became an American staple, what can be said is that they are delicious when made right.',
    },
    {
      id: 2,
      title: 'Masala Bhindi [lunch]',
      category: 'lunch',
      price: 53.99,
      img: './images/item-2.jpeg',
      desc: 'A North Indian curried dish featuring tender okra pods, piquant onions, tangy tomatoes, bold spices and herbs.Gluten-free and vegan.Healthy semi-dry spiced okra curry ',
    },
    {
      id: 3,
      title: 'Juicy chicken 65 [dinner]',
      category: 'dinner',
      price: 56.99,
      img: './images/item-3.jpeg',
      desc: `Chicken 65 is a popular chicken dish across india.Marinated chicken is then deep fried till cooked and crispy. Fried chicken is served as it is or tossed in a spicy sauce.`,
    },
    {
      id: 4,
      title: 'Avocado Toast [breakfast]',
      category: 'breakfast',
      price: 30.99,
      img: './images/item-4.jpeg',
      desc: 'Avocado contains a lot of heart-healthy unsaturated fats, as well as a good amount of fiber," Arrindell explains. ... "Whole grain bread has more fiber, protein, vitamins and minerals than white bread.',
    },
    {
      id: 5,
      title: 'Chana Kulcha [lunch]',
      category: 'lunch',
      price: 32.99,
      img: './images/item-5.jpeg',
      desc: `Chole kulcha is popular street food in India. The tasty chole curry served with soft and fluffy plain kulcha combo loved by all kinds of age groups.`,
    },
    {
      id: 6,
      title: 'Spaghetti [dinner]',
      category: 'dinner',
      price: 28.99,
      img: './images/item-6.jpeg',
      desc: ' The most popular of all the pasta types. It is the favorite of many, especially kids. Indeed, this is one of the most frequently cooked pasta worldwide.',
    },
    {
      id: 7,
      title: 'Home Fries [breakfast]',
      category: 'breakfast',
      price: 78.99,
      img: './images/item-7.jpeg',
      desc: `home fries are just potatoes that have been cut up into chunks, slices, small cubes, or wedges and fried in vegetable oil or butter in a skillet or pan. `,
    },
    {
      id: 8,
      title: 'Shahi Egg Curry [lunch]',
      category: 'lunch',
      price: 82.99,
      img: './images/item-8.jpeg',
      desc: ` A flavourful Egg curry is delicious and good to eat.The most tastiest food with soft and fluffy cooked one.`,
    },
    {
      id: 9,
      title: 'Chettinad fish fry [dinner]',
      category: 'dinner',
      price: 46.99,
      img: './images/item-9.jpeg',
      desc: `Try this fish fry .Thus it is a mild-tasting versatile fish allows seasoning and batters.`,
    },
    {
      id: 10,
      title: 'Cereal [breakfast]',
      category: 'breakfast',
      price: 26.00,
      img: './images/item-10.jpeg',
      desc: `A grain used for food,cultivated from edible components,natural and unprogressed.`,
    },
    {
      id: 11,
      title: 'Gujarati Kadhi [lunch]',
      category: 'lunch',
      price: 45.00,
      img: './images/item-11.jpeg',
      desc: `Gujarathi version of kadhi made from buttermilk  or dahi or gram flour.Essential part of Gujarathi cuisine.`,
    },
    {
      id: 12,
      title: 'Keema biriyani [dinner]',
      category: 'dinner',
      price: 39.00,
      img: './images/item-12.jpeg',
      desc: `It is a subtly spiced Biriyani that combines perfectly cooked,flavorful meat with Indian spices and Long grain.`,
    },
    {
      id: 13,
      title: 'Breakfast Wrap [breakfast]',
      category: 'breakfast',
      price: 56.00,
      img: './images/item-13.jpeg',
      desc: `Best way to kickstart your morning.It is a love because it is fun,freash,filling and healthy.`,
    },
    {
      id: 14,
      title: 'Allahabad Ki Tehri [lunch]',
      category: 'lunch',
      price: 29.67,
      img: './images/item-14.jpeg',
      desc: `A delicious one pot rice meal which is aromatic,filled with varied masalas and lots of vegetables.`,
    },
    {
      id: 15,
      title: 'Yogurt with fruits [dinner]',
      category: 'dinner',
      price: 32.99,
      img: './images/item-15.jpeg',
      desc: `Yogurt and fruits can be eaten together and may exert combined health benefits through potential effects.`,
    },
    {
      id: 16,
      title: 'Breakfast Sandwich [breakfast]',
      category: 'breakfast',
      price: 45.99,
      img: './images/item-16.jpeg',
      desc: `Sandwich filled with foods associated with the breakfast meal.It is served as fast food restaurants.`,
    },
    {
      id: 17,
      title: 'Meals [lunch]',
      category: 'lunch',
      price: 100.00,
      img: './images/item-17.jpeg',
      desc: `Most varieties under meals and a combination of more healthy items.`,
    },
    {
      id: 18,
      title: 'Prawn curry [dinner]',
      category: 'dinner',
      price: 560.00,
      img: './images/item-18.jpeg',
      desc: ` A flavourful Prawn curry is delicious and good to eat.The most tastiest food with soft and fluffy cooked one.`,
    },
    {
      id: 19,
      title: 'French Toast [breakfast]',
      category: 'breakfast',
      price: 196.99,
      img: './images/item-19.jpeg',
      desc: `Dish made of sliced bread soaked in beaten eggs and typically milk,then pan fried`,
    },
    {
      id: 20,
      title: 'Low Fat Dahi Chicken [lunch]',
      category: 'lunch',
      price: 160.50,
      img: './images/item-20.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 21,
      title: 'Chicken curry [dinner]',
      category: 'dinner',
      price: 160.50,
      img: './images/item31.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 22,
      title: 'Cereal [breakfast]',
      category: 'breakfast',
      price: 160.50,
      img: './images/item32.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 23,
      title: 'Biriyani rice [lunch]',
      category: 'lunch',
      price: 160.50,
      img: './images/item33.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 24,
      title: 'Stir fry [dinner]',
      category: 'dinner',
      price: 160.50,
      img: './images/item34.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 25,
      title: 'Doughnut [breakfast]',
      category: 'breakfast',
      price: 160.50,
      img: './images/item35.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 26,
      title: 'Mango rice [lunch]',
      category: 'lunch',
      price: 160.50,
      img: './images/item36.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 27,
      title: 'Burgers [dinner]',
      category: 'dinner',
      price: 160.50,
      img: './images/item37.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 28,
      title: 'Oat meal [breakfast]',
      category: 'breakfast',
      price: 160.50,
      img: './images/item38.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 29,
      title: 'Akki roti [lunch]',
      category: 'lunch',
      price: 160.50,
      img: './images/item39.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 30,
      title: 'Meatballs and rice [dinner]',
      category: 'dinner',
      price: 160.50,
      img: './images/item40.jpeg',
      desc: `Regular chicken as there are only nourishning great ingedients packed.`,
    },
    {
      id: 31,
      title: 'Asian cured salmon with prawns [starter]',
      category: 'starter',
      price: 340.00,
      img: './images/item-21.jpeg',
      desc: `Asian Item with low fat ingredients nourishing cells and as fried beeten one.`,
    },
    {
      id: 32,
      title: 'Vegetable gyoza [starter]',
      category: 'starter',
      price: 450.99,
      img: './images/item-22.jpeg',
      desc: `Stuffed with delicious mix of tofu,cabbage,carrots and shiitake mushrooms.With golden crisp bottom,fresh juict filling.`,
    },
    {
      id: 33,
      title: 'Charred spring onions [starter]',
      category: 'starter',
      price: 780.00,
      img: './images/item-23.jpeg',
      desc: `By trimming the top greens to fit if needed.with adding butter tender very tasty.`,
    },
    {
      id: 34,
      title: 'Holloumi, carrot and orange salad [starter]',
      category: 'starter',
      price: 569.99,
      img: './images/item-24.jpeg',
      desc: `This ia a cooling salad sings with summery flavour and many textures.Adding different types of melon,with citrus fruit also works as a treat.`,
    },
    {
      id: 35,
      title: 'Beetroot and walnut terrine [starter]',
      category: 'starter',
      price: 670.99,
      img: './images/item-25.jpeg',
      desc: `A delicious treat as a beetroot and walnut terrine combines.keep healthy and young as always as.`,
    },
    {
      id: 36,
      title: 'Pamplemousse [drinks]',
      category: 'drinks',
      price: 450.00,
      img: './images/item-26.jpeg',
      desc: `It is a grapefruit and  a grapefruit liquer.`,
    },
    {
      id: 37,
      title: 'Paloma [drinks]',
      category: 'drinks',
      price: 59.99,
      img: './images/item-27.jpeg',
      desc: `It is a tequila-based cocktail.Prepared by mixing ,lime juice and a grape-fruit.`,
    },
    {
      id: 38,
      title: 'Digestifs [drinks]',
      category: 'drinks',
      price: 300.00,
      img: './images/item-28.jpeg',
      desc: `A drink served after dinner.`,
    },
    {
      id: 39,
      title: 'Americano [drinks]',
      category: 'drinks',
      price: 340.00,
      img: './images/item-29.jpeg',
      desc: `Cocktail composed of sparkling version,club soda and garnished with slice of lemon.`,
    },
    {
      id: 40,
      title: 'Tonic [drinks]',
      category: 'drinks',
      price: 255.00,
      img: './images/item-30.jpeg',
      desc: `Refreshing drink is a staple for spring and summer gets together.`,
    },
    
  ];
  export default menu;